package com.example.universitySE.domain;
// Generated 29-gen-2019 18.51.31 by Hibernate Tools 5.2.0.Final


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * ActivityType generated by hbm2java
 */
@Entity
@Table(name="Activity_type"
    ,catalog="se_database"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class ActivityType  implements java.io.Serializable {


     private Integer id;
     private String name;

    public ActivityType() {
    }

    public ActivityType(String name) {
       this.name = name;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", unique=true, nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


