package com.example.universitySE.domain;
// Generated 3-feb-2019 20.09.13 by Hibernate Tools 5.2.0.Final


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * CarryoutActivity generated by hbm2java
 */
@Entity
@Table(name="Carryout_activity"
    ,catalog="se_database"
)
public class CarryoutActivity  implements java.io.Serializable {


     private long id;
     private int idActivity;
     private int classroomName;

    public CarryoutActivity() {
    }

    public CarryoutActivity(int idActivity, int classroomName) {
       this.idActivity = idActivity;
       this.classroomName = classroomName;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="id_activity", nullable=false)
    public int getIdActivity() {
        return this.idActivity;
    }
    
    public void setIdActivity(int idActivity) {
        this.idActivity = idActivity;
    }

    
    @Column(name="classroom_name", nullable=false)
    public int getClassroomName() {
        return this.classroomName;
    }
    
    public void setClassroomName(int classroomName) {
        this.classroomName = classroomName;
    }




}


