package com.example.universitySE.domain;
// Generated 2-feb-2019 18.45.35 by Hibernate Tools 5.2.0.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ExchangeMessage generated by hbm2java
 */
@Entity
@Table(name="Exchange_message"
    ,catalog="se_database"
)
public class ExchangeMessage  implements java.io.Serializable {


     private Integer id;
     private Date date;
     private int sender;
     private int receiver;
     private int idMessage;

    public ExchangeMessage() {
    }

    public ExchangeMessage(Date date, int sender, int receiver, int idMessage) {
       this.date = date;
       this.sender = sender;
       this.receiver = receiver;
       this.idMessage = idMessage;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="sender", nullable=false)
    public int getSender() {
        return this.sender;
    }
    
    public void setSender(int sender) {
        this.sender = sender;
    }

    
    @Column(name="receiver", nullable=false)
    public int getReceiver() {
        return this.receiver;
    }
    
    public void setReceiver(int receiver) {
        this.receiver = receiver;
    }

    
    @Column(name="id_message", nullable=false)
    public int getIdMessage() {
        return this.idMessage;
    }
    
    public void setIdMessage(int idMessage) {
        this.idMessage = idMessage;
    }




}


