package com.example.universitySE.domain;
// Generated 2-feb-2019 18.39.07 by Hibernate Tools 5.2.0.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Lesson generated by hbm2java
 */
@Entity
@Table(name="Lesson"
    ,catalog="se_database"
)
public class Lesson  implements java.io.Serializable {


     private long id;

    public Lesson() {
    }

    public Lesson(long id) {
       this.id = id;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }




}


