package com.example.universitySE.domain;
// Generated 28-gen-2019 15.27.48 by Hibernate Tools 5.2.0.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name="Message"
    ,catalog="se_database"
)
public class Message  implements java.io.Serializable {


     private int id;
     private String content;
     private int subject;

    public Message() {
    }

    public Message(int id, String content, int subject) {
       this.id = id;
       this.content = content;
       this.subject = subject;
    }
   
     @Id

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="content", nullable=false)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    
    @Column(name="subject", nullable=false)
    public int getSubject() {
        return this.subject;
    }
    
    public void setSubject(int subject) {
        this.subject = subject;
    }




}


