package com.example.universitySE.domain;
// Generated 24-gen-2019 10.24.28 by Hibernate Tools 5.2.0.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name="Person"
    ,catalog="se_database"
)
public class Person  implements java.io.Serializable {


     private int id;
     private String username;
     private String password;
     private int personType;

    public Person() {
    }

    public Person(int id, String username, String password, int personType) {
       this.id = id;
       this.username = username;
       this.password = password;
       this.personType = personType;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="username", nullable=false)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="person_type", nullable=false)
    public int getPersonType() {
        return this.personType;
    }
    
    public void setPersonType(int personType) {
        this.personType = personType;
    }




}


