package com.example.universitySE.domain;
// Generated 14-feb-2019 21.58.38 by Hibernate Tools 5.2.0.Final


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name="Person"
    ,catalog="se_database"
    , uniqueConstraints = @UniqueConstraint(columnNames="username") 
)
public class Person  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private int personType;

    public Person() {
    }

    public Person(String username, String password, int personType) {
       this.username = username;
       this.password = password;
       this.personType = personType;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="username", unique=true, nullable=false)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="person_type", nullable=false)
    public int getPersonType() {
        return this.personType;
    }
    
    public void setPersonType(int personType) {
        this.personType = personType;
    }




}


