package com.example.universitySE.domain;
// Generated 28-gen-2019 15.27.48 by Hibernate Tools 5.2.0.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Reporting generated by hbm2java
 */
@Entity
@Table(name="Reporting"
    ,catalog="se_database"
)
public class Reporting  implements java.io.Serializable {


     private int id;
     private String noteProf;
     private int supportMaterialProf;
     private String noteSec;
     private int state;

    public Reporting() {
    }

    public Reporting(int id, String noteProf, int supportMaterialProf, String noteSec, int state) {
       this.id = id;
       this.noteProf = noteProf;
       this.supportMaterialProf = supportMaterialProf;
       this.noteSec = noteSec;
       this.state = state;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="note_prof", nullable=false, length=65535)
    public String getNoteProf() {
        return this.noteProf;
    }
    
    public void setNoteProf(String noteProf) {
        this.noteProf = noteProf;
    }

    
    @Column(name="support_material_prof", nullable=false)
    public int getSupportMaterialProf() {
        return this.supportMaterialProf;
    }
    
    public void setSupportMaterialProf(int supportMaterialProf) {
        this.supportMaterialProf = supportMaterialProf;
    }

    
    @Column(name="note_sec", nullable=false, length=65535)
    public String getNoteSec() {
        return this.noteSec;
    }
    
    public void setNoteSec(String noteSec) {
        this.noteSec = noteSec;
    }

    
    @Column(name="state", nullable=false)
    public int getState() {
        return this.state;
    }
    
    public void setState(int state) {
        this.state = state;
    }




}


