package com.example.universitySE.domain;
// Generated 14-feb-2019 21.58.38 by Hibernate Tools 5.2.0.Final


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * State generated by hbm2java
 */
@Entity
@Table(name="State"
    ,catalog="se_database"
)
public class State  implements java.io.Serializable {


     private Integer id;
     private String name;

    public State() {
    }

    public State(String name) {
       this.name = name;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


