package com.example.universitySE.domain;
// Generated 2-feb-2019 18.45.35 by Hibernate Tools 5.2.0.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name="Student"
    ,catalog="se_database"
    , uniqueConstraints = @UniqueConstraint(columnNames="badge_number") 
)
public class Student  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastName;
     private Date dateOfBirth;
     private int badgeNumber;
     private int studyCourse;
     private Date enrollmentYear;

    public Student() {
    }

    public Student(String firstName, String lastName, Date dateOfBirth, int badgeNumber, int studyCourse, Date enrollmentYear) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.dateOfBirth = dateOfBirth;
       this.badgeNumber = badgeNumber;
       this.studyCourse = studyCourse;
       this.enrollmentYear = enrollmentYear;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="first_name", nullable=false)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", nullable=false)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_of_birth", nullable=false, length=10)
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    
    @Column(name="badge_number", unique=true, nullable=false)
    public int getBadgeNumber() {
        return this.badgeNumber;
    }
    
    public void setBadgeNumber(int badgeNumber) {
        this.badgeNumber = badgeNumber;
    }

    
    @Column(name="study_course", nullable=false)
    public int getStudyCourse() {
        return this.studyCourse;
    }
    
    public void setStudyCourse(int studyCourse) {
        this.studyCourse = studyCourse;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="enrollment_year", nullable=false, length=10)
    public Date getEnrollmentYear() {
        return this.enrollmentYear;
    }
    
    public void setEnrollmentYear(Date enrollmentYear) {
        this.enrollmentYear = enrollmentYear;
    }




}


