package com.example.universitySE.domain;
// Generated 3-feb-2019 20.09.13 by Hibernate Tools 5.2.0.Final


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * StudyCourse generated by hbm2java
 */
@Entity
@Table(name="Study_course"
    ,catalog="se_database"
)
public class StudyCourse  implements java.io.Serializable {


     private long id;
     private String name;
     private long faculty;

    public StudyCourse() {
    }

    public StudyCourse(String name, long faculty) {
       this.name = name;
       this.faculty = faculty;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="faculty", nullable=false)
    public long getFaculty() {
        return this.faculty;
    }
    
    public void setFaculty(long faculty) {
        this.faculty = faculty;
    }




}


